# Generated by Django 3.0.6 on 2020-05-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='image',
            new_name='img',
        ),
    ]
